### ISSUE TITLE
Sentiment range

### ISSUE THREAD

**Issue by amalinazakaria** [AsyrafAzlan/SentiLexM#1]
Hi, I wanna ask. The sentiment scores range is between +5 and -5. So until what range is positive, negative and neutral?

**Comment by asyraf-azlan** [comment]
Hi @amalinazakaria , thanks for the question.
In the application of my conference paper, I used the following:
Negative: -5 to -1
Neutral: 0
Positive:  +1 to +5

As the dictionary text file only consists of word/score combination, the range could be up to your interpretation as well and depends on your application.  E.g. Neutral => +1, 0, 1.

**Comment by AsyrafAzlan** [comment]
Hi @amalinazakaria , thanks for the question.
In the application of my conference paper, I used the following:
Negative: -5 to -1
Neutral: 0
Positive: +1 to +5

As the dictionary text file only consists of word/score combination, the range could be up to your interpretation as well and depends on your application. E.g. Neutral => +1, 0, 1.
